### ISSUE TITLE
Exception while building

### ISSUE THREAD

**Issue by oieadmin** [antoineleclair/slack-exporter#1]
Hi @antoineleclair ,

I tried to build but got an exception. Looks like it can't find the "jspm_packages" directory. Wondering if it's something to do with my environment. thx

```
$ gulp
[07:58:03] Using gulpfile ~/Downloads/slack-exporter-master/gulpfile.js
[07:58:03] Starting 'build:spy'...
[07:58:03] Starting 'build:background'...
[07:58:03] Starting 'copy:vendor'...
[07:58:03] Starting 'copy:manifest'...
[07:58:03] Starting 'copy:injector'...
[07:58:03] Starting 'copy:dropbox-oauth-receiver'...
[07:58:03] Starting 'copy:popup'...
[07:58:05] Finished 'copy:injector' after 1.13 s
[07:58:05] Finished 'copy:manifest' after 1.14 s
[07:58:05] Finished 'copy:popup' after 1.13 s
[07:58:05] Finished 'copy:vendor' after 1.14 s
gulp-jspm: Error: Error on translate for src/spy/main.js at file:///Users/chriswebb/Downloads/slack-exporter-master/src/spy/main.js
	(SystemJS) ENOENT: no such file or directory, open '/Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js'
	Error: ENOENT: no such file or directory, open '/Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js'
	Error loading /Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js
	Unable to load transpiler to transpile /Users/chriswebb/Downloads/slack-exporter-master/src/spy/main.js
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:496:10
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:455:8
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:421:6
    at Trace.getLoadRecord (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:260:33
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (native)
    at processExpandedOperations (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
    at exports.traceExpression (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:766:14
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:765:6
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:213:26
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:576:13
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:421:6
From previous event:
    at Trace.getLoadRecord (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:260:33
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (native)
    at processExpandedOperations (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
From previous event:
    at exports.traceExpression (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:766:14
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:765:6
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:213:26
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
gulp-jspm: Error: Error on translate for src/background/main.js at file:///Users/chriswebb/Downloads/slack-exporter-master/src/background/main.js
	(SystemJS) ENOENT: no such file or directory, open '/Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js'
	Error: ENOENT: no such file or directory, open '/Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js'
	Error loading /Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js
	Unable to load transpiler to transpile /Users/chriswebb/Downloads/slack-exporter-master/src/background/main.js
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:496:10
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:455:8
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:421:6
    at Trace.getLoadRecord (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:260:33
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (native)
    at processExpandedOperations (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
    at exports.traceExpression (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:766:14
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:765:6
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:213:26
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:576:13
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:421:6
From previous event:
    at Trace.getLoadRecord (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:260:33
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (native)
    at processExpandedOperations (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
From previous event:
    at exports.traceExpression (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:766:14
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:765:6
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:213:26
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
[07:58:05] Finished 'copy:dropbox-oauth-receiver' after 1.15 s
[07:58:05] Starting 'copy'...
[07:58:05] Finished 'copy' after 23 μs

events.js:161
      throw er; // Unhandled 'error' event
      ^
Error: Error on translate for src/spy/main.js at file:///Users/chriswebb/Downloads/slack-exporter-master/src/spy/main.js
	(SystemJS) ENOENT: no such file or directory, open '/Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js'
	Error: ENOENT: no such file or directory, open '/Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js'
	Error loading /Users/chriswebb/Downloads/slack-exporter-master/jspm_packages/npm/babel-core@5.8.38.js
	Unable to load transpiler to transpile /Users/chriswebb/Downloads/slack-exporter-master/src/spy/main.js
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:496:10
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:455:8
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:421:6
    at Trace.getLoadRecord (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:260:33
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (native)
    at processExpandedOperations (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
    at exports.traceExpression (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:766:14
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:765:6
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:213:26
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:576:13
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:421:6
From previous event:
    at Trace.getLoadRecord (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:260:33
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (native)
    at processExpandedOperations (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
From previous event:
    at exports.traceExpression (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:766:14
From previous event:
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:765:6
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/chriswebb/Downloads/slack-exporter-master/node_modules/jspm/lib/bundle.js:213:26
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by antoineleclair** [comment]
Oh, right, the README should probably contain that information:

You have to install the jspm packages as well:

    jspm install

Or maybe it's in the node_modules somewhere, like `nodemodules/jpsm/bin/cli.js install`.

If you have time to update the README it would be great.

**Comment by oieadmin** [comment]
Hi @antoineleclair,

Yes you're right, I managed to get it working by running the following commands taken from the [jspm documentation](http://jspm.io/docs/getting-started.html)...
```
$ npm install jspm -g
$ jspm install
```

I'll have a look at updating the README. Thanks for the help.
